--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-10-15 19:49:54

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 227 (class 1259 OID 49303)
-- Name: department; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.department (
    id bigint NOT NULL,
    d_name character varying(255),
    hod_id bigint
);


ALTER TABLE public.department OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 49306)
-- Name: department_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.department ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.department_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4942 (class 0 OID 49303)
-- Dependencies: 227
-- Data for Name: department; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.department VALUES (3, 'Commerce', NULL);
INSERT INTO public.department VALUES (5, 'Chemistry', NULL);
INSERT INTO public.department VALUES (4, 'Arts', NULL);
INSERT INTO public.department VALUES (2, 'Computer Applications', 23);
INSERT INTO public.department VALUES (1, 'Computer Science and Engineering', 29);
INSERT INTO public.department VALUES (6, 'Mechanical Engineering', NULL);
INSERT INTO public.department VALUES (7, 'Electrical and Electronics Engineering', NULL);
INSERT INTO public.department VALUES (8, 'Electronics and Communications Engineering', NULL);
INSERT INTO public.department VALUES (9, 'Management', NULL);
INSERT INTO public.department VALUES (10, 'Physics', NULL);
INSERT INTO public.department VALUES (11, 'Mathematics', NULL);
INSERT INTO public.department VALUES (12, 'Bio-Sciences', NULL);
INSERT INTO public.department VALUES (13, 'Botany', NULL);
INSERT INTO public.department VALUES (14, 'Zoology', NULL);
INSERT INTO public.department VALUES (15, 'Pharmacy', NULL);
INSERT INTO public.department VALUES (16, 'Social Work', NULL);
INSERT INTO public.department VALUES (17, 'Psychology', NULL);
INSERT INTO public.department VALUES (18, 'Education', NULL);
INSERT INTO public.department VALUES (19, 'Mass Communication', NULL);
INSERT INTO public.department VALUES (20, 'English', NULL);
INSERT INTO public.department VALUES (21, 'Philosophy', NULL);
INSERT INTO public.department VALUES (22, 'Economics', NULL);
INSERT INTO public.department VALUES (23, 'North East India Studies', NULL);
INSERT INTO public.department VALUES (24, 'Comparative Religion', NULL);
INSERT INTO public.department VALUES (25, 'Public Administration', NULL);
INSERT INTO public.department VALUES (26, 'Hospitality and Hotel Administration', NULL);


--
-- TOC entry 4949 (class 0 OID 0)
-- Dependencies: 228
-- Name: department_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.department_id_seq', 26, true);


--
-- TOC entry 4795 (class 2606 OID 49351)
-- Name: department department_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT department_pkey PRIMARY KEY (id);


--
-- TOC entry 4796 (class 2606 OID 49503)
-- Name: department hod_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT hod_id FOREIGN KEY (hod_id) REFERENCES public.professor(id) ON DELETE SET NULL;


-- Completed on 2025-10-15 19:49:55

--
-- PostgreSQL database dump complete
--

