--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-10-15 12:13:46

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 237980)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 237981)
-- Name: attendance; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.attendance (
    class_id bigint NOT NULL,
    date date NOT NULL,
    st_id bigint NOT NULL,
    "time" time(6) without time zone NOT NULL
);


ALTER TABLE public.attendance OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 237987)
-- Name: branch; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.branch (
    id bigint NOT NULL,
    branch_name character varying(255),
    dept_id bigint
);


ALTER TABLE public.branch OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 254083)
-- Name: branch_class_courses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.branch_class_courses (
    branch_id bigint NOT NULL,
    class_courses_id bigint NOT NULL
);


ALTER TABLE public.branch_class_courses OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 237986)
-- Name: branch_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.branch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.branch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 237993)
-- Name: class; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.class (
    id bigint NOT NULL,
    day character varying(255),
    semester bigint NOT NULL,
    "time" time(6) without time zone,
    class_course_id bigint,
    prof_id bigint,
    branch_id bigint
);


ALTER TABLE public.class OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 237992)
-- Name: class_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.class ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.class_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 237999)
-- Name: course; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.course (
    id bigint NOT NULL,
    course_name character varying(255),
    credit bigint,
    dept_id bigint
);


ALTER TABLE public.course OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 237998)
-- Name: course_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 238004)
-- Name: course_professor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.course_professor (
    prof_id bigint NOT NULL,
    course_id bigint NOT NULL
);


ALTER TABLE public.course_professor OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 238007)
-- Name: course_student; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.course_student (
    st_id bigint NOT NULL,
    course_id bigint NOT NULL
);


ALTER TABLE public.course_student OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 238011)
-- Name: department; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.department (
    id bigint NOT NULL,
    d_name character varying(255),
    hod_id bigint
);


ALTER TABLE public.department OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 238010)
-- Name: department_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.department ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.department_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 238017)
-- Name: professor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.professor (
    id bigint NOT NULL,
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    dept_id bigint,
    user_id bigint
);


ALTER TABLE public.professor OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 238016)
-- Name: professor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.professor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.professor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 238025)
-- Name: role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role (
    id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.role OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 238024)
-- Name: role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 238031)
-- Name: student; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student (
    id bigint NOT NULL,
    emailid character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    semester bigint,
    branch_id bigint,
    user_id bigint
);


ALTER TABLE public.student OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 238038)
-- Name: student_class; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_class (
    class_id bigint NOT NULL,
    st_id bigint NOT NULL
);


ALTER TABLE public.student_class OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 238030)
-- Name: student_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.student ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 238044)
-- Name: test; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.test (
    id bigint NOT NULL,
    date date,
    "time" time(6) without time zone,
    total_marks bigint NOT NULL,
    class_id bigint,
    course_id bigint,
    prof_id bigint
);


ALTER TABLE public.test OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 238043)
-- Name: test_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.test ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.test_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 238049)
-- Name: test_student; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.test_student (
    test_studentid character varying(255) NOT NULL,
    marks bigint,
    st_id bigint,
    test_id bigint
);


ALTER TABLE public.test_student OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 238058)
-- Name: user_data; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_data (
    id bigint NOT NULL,
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    password character varying(255)
);


ALTER TABLE public.user_data OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 238057)
-- Name: user_data_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 238054)
-- Name: user_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    roles_id bigint NOT NULL
);


ALTER TABLE public.user_roles OWNER TO postgres;

--
-- TOC entry 5018 (class 0 OID 237981)
-- Dependencies: 217
-- Data for Name: attendance; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5020 (class 0 OID 237987)
-- Dependencies: 219
-- Data for Name: branch; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.branch VALUES (1, 'Bachelor of Computer Applications', 2);
INSERT INTO public.branch VALUES (2, 'Master of Computer Applications', 2);
INSERT INTO public.branch VALUES (3, 'Bachelor of Computer Science and Engineering', 1);
INSERT INTO public.branch VALUES (4, 'Master of Computer Science and Engineering', 1);


--
-- TOC entry 5042 (class 0 OID 254083)
-- Dependencies: 241
-- Data for Name: branch_class_courses; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5022 (class 0 OID 237993)
-- Dependencies: 221
-- Data for Name: class; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.class VALUES (5, 'Friday', 1, '14:00:00', 9, 24, 1);
INSERT INTO public.class VALUES (6, 'Friday', 1, '15:00:00', 7, 24, 2);
INSERT INTO public.class VALUES (1, 'Friday', 1, '17:00:00', 1, 23, 1);
INSERT INTO public.class VALUES (4, 'Friday', 1, '14:00:00', 3, 24, 1);
INSERT INTO public.class VALUES (3, 'Friday', 1, '13:00:00', 2, 24, 1);
INSERT INTO public.class VALUES (2, 'Friday', 1, '18:30:00', 1, 23, 1);
INSERT INTO public.class VALUES (7, 'Monday', 1, '10:00:00', 1, 24, 1);
INSERT INTO public.class VALUES (8, 'Monday', 1, '11:45:00', 1, 24, 1);


--
-- TOC entry 5024 (class 0 OID 237999)
-- Dependencies: 223
-- Data for Name: course; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.course VALUES (1, 'Introduction to Java', 50, 2);
INSERT INTO public.course VALUES (2, 'Software Engineering', 50, 2);
INSERT INTO public.course VALUES (3, 'Data Structure and Algorithms', 50, 2);
INSERT INTO public.course VALUES (4, 'Internet of Things', 50, 1);
INSERT INTO public.course VALUES (5, 'Computer Organisation and Architecture', 50, 1);
INSERT INTO public.course VALUES (6, 'Digital Logic and Design', 50, 1);
INSERT INTO public.course VALUES (7, 'Database and Management Systems', 50, 2);
INSERT INTO public.course VALUES (8, 'Operating Systems', 50, 2);
INSERT INTO public.course VALUES (9, 'Data Communication and Networks I', 50, 2);
INSERT INTO public.course VALUES (10, 'Data Communication and Networks II', 50, 2);


--
-- TOC entry 5025 (class 0 OID 238004)
-- Dependencies: 224
-- Data for Name: course_professor; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.course_professor VALUES (23, 1);
INSERT INTO public.course_professor VALUES (23, 2);
INSERT INTO public.course_professor VALUES (23, 3);
INSERT INTO public.course_professor VALUES (24, 1);
INSERT INTO public.course_professor VALUES (24, 2);
INSERT INTO public.course_professor VALUES (24, 3);
INSERT INTO public.course_professor VALUES (25, 1);
INSERT INTO public.course_professor VALUES (25, 2);
INSERT INTO public.course_professor VALUES (25, 3);
INSERT INTO public.course_professor VALUES (29, 6);
INSERT INTO public.course_professor VALUES (29, 5);
INSERT INTO public.course_professor VALUES (29, 4);


--
-- TOC entry 5026 (class 0 OID 238007)
-- Dependencies: 225
-- Data for Name: course_student; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.course_student VALUES (3, 1);
INSERT INTO public.course_student VALUES (3, 2);
INSERT INTO public.course_student VALUES (4, 1);
INSERT INTO public.course_student VALUES (4, 2);
INSERT INTO public.course_student VALUES (4, 3);
INSERT INTO public.course_student VALUES (5, 1);
INSERT INTO public.course_student VALUES (5, 2);
INSERT INTO public.course_student VALUES (5, 3);
INSERT INTO public.course_student VALUES (6, 1);
INSERT INTO public.course_student VALUES (6, 2);
INSERT INTO public.course_student VALUES (6, 3);
INSERT INTO public.course_student VALUES (7, 1);
INSERT INTO public.course_student VALUES (7, 2);
INSERT INTO public.course_student VALUES (7, 3);


--
-- TOC entry 5028 (class 0 OID 238011)
-- Dependencies: 227
-- Data for Name: department; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.department VALUES (3, 'Commerce', NULL);
INSERT INTO public.department VALUES (5, 'Chemistry', NULL);
INSERT INTO public.department VALUES (4, 'Arts', NULL);
INSERT INTO public.department VALUES (2, 'Computer Applications', 23);
INSERT INTO public.department VALUES (1, 'Computer Science and Engineering', 29);


--
-- TOC entry 5030 (class 0 OID 238017)
-- Dependencies: 229
-- Data for Name: professor; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.professor VALUES (23, 'ronlaflamme@gmail.com', 'Ron', 'Laflamme', 2, 29);
INSERT INTO public.professor VALUES (24, 'richardhendricks@gmail.com', 'Richard', 'Hendricks', 2, 30);
INSERT INTO public.professor VALUES (25, 'erlichbachman@gmail.com', 'Erlich', 'Bachman', 2, 31);
INSERT INTO public.professor VALUES (27, 'mortaddams@gmail.com', 'Morticia', 'Addams', 1, 37);
INSERT INTO public.professor VALUES (29, 'gomezaddams@gmail.com', 'Gomez', 'Addams', 1, 40);


--
-- TOC entry 5032 (class 0 OID 238025)
-- Dependencies: 231
-- Data for Name: role; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.role VALUES (1, 'Admin');
INSERT INTO public.role VALUES (3, 'Student');
INSERT INTO public.role VALUES (4, 'Head Of Department');
INSERT INTO public.role VALUES (6, 'Professor');


--
-- TOC entry 5034 (class 0 OID 238031)
-- Dependencies: 233
-- Data for Name: student; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.student VALUES (3, 'lauriebream@gmail.com', 'Laurie', 'Bream', 1, 1, 26);
INSERT INTO public.student VALUES (4, 'nelsonbighead@gmail.com', 'Nelson', 'Bighetti', 1, 1, 32);
INSERT INTO public.student VALUES (5, 'jennaortega@gmail.com', 'Jenna', 'Ortega', 1, 1, 33);
INSERT INTO public.student VALUES (6, 'wednesdayaddams@gmail.com', 'Wednesday', 'Addams', 1, 1, 34);
INSERT INTO public.student VALUES (7, 'enidwolf@gmail.com', 'Enid', 'Wolf', 1, 1, 35);


--
-- TOC entry 5035 (class 0 OID 238038)
-- Dependencies: 234
-- Data for Name: student_class; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.student_class VALUES (3, 3);
INSERT INTO public.student_class VALUES (4, 3);
INSERT INTO public.student_class VALUES (1, 3);
INSERT INTO public.student_class VALUES (3, 4);
INSERT INTO public.student_class VALUES (4, 4);
INSERT INTO public.student_class VALUES (1, 4);
INSERT INTO public.student_class VALUES (3, 5);
INSERT INTO public.student_class VALUES (4, 5);
INSERT INTO public.student_class VALUES (1, 5);
INSERT INTO public.student_class VALUES (2, 5);
INSERT INTO public.student_class VALUES (3, 6);
INSERT INTO public.student_class VALUES (4, 6);
INSERT INTO public.student_class VALUES (1, 6);
INSERT INTO public.student_class VALUES (2, 6);
INSERT INTO public.student_class VALUES (3, 7);
INSERT INTO public.student_class VALUES (4, 7);
INSERT INTO public.student_class VALUES (1, 7);
INSERT INTO public.student_class VALUES (2, 7);
INSERT INTO public.student_class VALUES (2, 3);
INSERT INTO public.student_class VALUES (5, 3);
INSERT INTO public.student_class VALUES (7, 3);
INSERT INTO public.student_class VALUES (8, 3);


--
-- TOC entry 5037 (class 0 OID 238044)
-- Dependencies: 236
-- Data for Name: test; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5038 (class 0 OID 238049)
-- Dependencies: 237
-- Data for Name: test_student; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5041 (class 0 OID 238058)
-- Dependencies: 240
-- Data for Name: user_data; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.user_data VALUES (1, 'admin@gmail.com', 'Larisa', 'Wahlang', '$2a$10$1kR4sJUdc/sGL7RvK2fd6OEWRYX6mmTgkn6orjKZwmOw0hv2IlDl.');
INSERT INTO public.user_data VALUES (26, 'lauriebream@gmail.com', 'Laurie', 'Bream', '$2a$10$19MHS3Kx7yOaW/RwuzR7CeCmACVzjz7.aZcB0sB7bPXDIzS/yF3Em');
INSERT INTO public.user_data VALUES (29, 'ronlaflamme@gmail.com', 'Ron', 'Laflamme', '$2a$10$6quBoM253fQxBBiMz9B0ZeX.U4tpq.KOmrzVeC39129oJZMECV9vm');
INSERT INTO public.user_data VALUES (30, 'richardhendricks@gmail.com', 'Richard', 'Hendricks', '$2a$10$MefuGEuXGcblyVhzORak0.zlOcukRsPPoqougkpdcglwsgKuCDa0u');
INSERT INTO public.user_data VALUES (31, 'erlichbachman@gmail.com', 'Erlich', 'Bachman', '$2a$10$DDx.8FjMh3zm8fdyDc4wuO3yNnd9jrR43UcvRf8IfkZ35EhBGoNui');
INSERT INTO public.user_data VALUES (32, 'nelsonbighead@gmail.com', 'Nelson', 'Bighetti', '$2a$10$s8lx55.nkxHXB1T7beIoWOWzPouFgNFb2wtfxHwyIcUJfMOUgAfTm');
INSERT INTO public.user_data VALUES (33, 'jennaortega@gmail.com', 'Jenna', 'Ortega', '$2a$10$e1BzxoEv9p2winADSuKdTeFytbVQU5gjQZaVxtlcN0DJ6r1bDY8sa');
INSERT INTO public.user_data VALUES (34, 'wednesdayaddams@gmail.com', 'Wednesday', 'Addams', '$2a$10$XPeGvhPW47cceP9q1zGnfuWP.0oaOz6GKdmfw.zhV6ql/3LK11qpK');
INSERT INTO public.user_data VALUES (35, 'enidwolf@gmail.com', 'Enid', 'Wolf', '$2a$10$PhjjkRgXxmnWrP/C68PmdeQoaTo0MrDvroGx/DZhFfP2oJt8xNEiS');
INSERT INTO public.user_data VALUES (37, 'mortaddams@gmail.com', 'Morticia', 'Addams', '$2a$10$AXUagg1.nAk8ceOEkv5gTeURIK4S2Pqnyu5ANN2A8oMsss1DXBz3m');
INSERT INTO public.user_data VALUES (40, 'gomezaddams@gmail.com', 'Gomez', 'Addams', '$2a$10$MAYu.VRAfFuXubWYtVpbieO0iClk4jCibrVG7WdjPLT8l4SNSA7Aa');


--
-- TOC entry 5039 (class 0 OID 238054)
-- Dependencies: 238
-- Data for Name: user_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.user_roles VALUES (1, 1);
INSERT INTO public.user_roles VALUES (26, 3);
INSERT INTO public.user_roles VALUES (29, 4);
INSERT INTO public.user_roles VALUES (30, 6);
INSERT INTO public.user_roles VALUES (31, 6);
INSERT INTO public.user_roles VALUES (32, 3);
INSERT INTO public.user_roles VALUES (33, 3);
INSERT INTO public.user_roles VALUES (34, 3);
INSERT INTO public.user_roles VALUES (35, 3);
INSERT INTO public.user_roles VALUES (37, 4);
INSERT INTO public.user_roles VALUES (40, 4);


--
-- TOC entry 5049 (class 0 OID 0)
-- Dependencies: 218
-- Name: branch_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.branch_id_seq', 4, true);


--
-- TOC entry 5050 (class 0 OID 0)
-- Dependencies: 220
-- Name: class_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.class_id_seq', 8, true);


--
-- TOC entry 5051 (class 0 OID 0)
-- Dependencies: 222
-- Name: course_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.course_id_seq', 10, true);


--
-- TOC entry 5052 (class 0 OID 0)
-- Dependencies: 226
-- Name: department_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.department_id_seq', 5, true);


--
-- TOC entry 5053 (class 0 OID 0)
-- Dependencies: 228
-- Name: professor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.professor_id_seq', 29, true);


--
-- TOC entry 5054 (class 0 OID 0)
-- Dependencies: 230
-- Name: role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.role_id_seq', 6, true);


--
-- TOC entry 5055 (class 0 OID 0)
-- Dependencies: 232
-- Name: student_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.student_id_seq', 7, true);


--
-- TOC entry 5056 (class 0 OID 0)
-- Dependencies: 235
-- Name: test_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.test_id_seq', 1, false);


--
-- TOC entry 5057 (class 0 OID 0)
-- Dependencies: 239
-- Name: user_data_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_data_id_seq', 40, true);


--
-- TOC entry 4811 (class 2606 OID 237985)
-- Name: attendance attendance_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT attendance_pkey PRIMARY KEY (class_id, date, st_id, "time");


--
-- TOC entry 4813 (class 2606 OID 237991)
-- Name: branch branch_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.branch
    ADD CONSTRAINT branch_pkey PRIMARY KEY (id);


--
-- TOC entry 4815 (class 2606 OID 237997)
-- Name: class class_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.class
    ADD CONSTRAINT class_pkey PRIMARY KEY (id);


--
-- TOC entry 4817 (class 2606 OID 238003)
-- Name: course course_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT course_pkey PRIMARY KEY (id);


--
-- TOC entry 4821 (class 2606 OID 238015)
-- Name: department department_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT department_pkey PRIMARY KEY (id);


--
-- TOC entry 4823 (class 2606 OID 238023)
-- Name: professor professor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.professor
    ADD CONSTRAINT professor_pkey PRIMARY KEY (id);


--
-- TOC entry 4827 (class 2606 OID 238029)
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- TOC entry 4835 (class 2606 OID 238042)
-- Name: student_class student_class_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_class
    ADD CONSTRAINT student_class_pkey PRIMARY KEY (class_id, st_id);


--
-- TOC entry 4829 (class 2606 OID 238037)
-- Name: student student_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_pkey PRIMARY KEY (id);


--
-- TOC entry 4837 (class 2606 OID 238048)
-- Name: test test_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.test
    ADD CONSTRAINT test_pkey PRIMARY KEY (id);


--
-- TOC entry 4839 (class 2606 OID 238053)
-- Name: test_student test_student_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.test_student
    ADD CONSTRAINT test_student_pkey PRIMARY KEY (test_studentid);


--
-- TOC entry 4819 (class 2606 OID 238066)
-- Name: course uk9dll001xc2cip6hug6axoab0p; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT uk9dll001xc2cip6hug6axoab0p UNIQUE (course_name);


--
-- TOC entry 4845 (class 2606 OID 254087)
-- Name: branch_class_courses uka5mbm7f4u8mjvtomqo238nekw; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.branch_class_courses
    ADD CONSTRAINT uka5mbm7f4u8mjvtomqo238nekw UNIQUE (class_courses_id);


--
-- TOC entry 4831 (class 2606 OID 238074)
-- Name: student ukbkix9btnoi1n917ll7bplkvg5; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT ukbkix9btnoi1n917ll7bplkvg5 UNIQUE (user_id);


--
-- TOC entry 4841 (class 2606 OID 238076)
-- Name: user_data ukdhxuydjj5l1vds6s9eex23dcr; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_data
    ADD CONSTRAINT ukdhxuydjj5l1vds6s9eex23dcr UNIQUE (email);


--
-- TOC entry 4833 (class 2606 OID 238072)
-- Name: student ukjbwyp9v38ln0f471avro4w7ca; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT ukjbwyp9v38ln0f471avro4w7ca UNIQUE (emailid);


--
-- TOC entry 4825 (class 2606 OID 238070)
-- Name: professor ukn3f1mi90f5bhejx5jlwwa0l2a; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.professor
    ADD CONSTRAINT ukn3f1mi90f5bhejx5jlwwa0l2a UNIQUE (user_id);


--
-- TOC entry 4843 (class 2606 OID 238064)
-- Name: user_data user_data_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_data
    ADD CONSTRAINT user_data_pkey PRIMARY KEY (id);


--
-- TOC entry 4849 (class 2606 OID 254078)
-- Name: class class_branch_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.class
    ADD CONSTRAINT class_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branch(id) ON DELETE SET NULL;


--
-- TOC entry 4860 (class 2606 OID 238142)
-- Name: student fk1c2wse5ythrh0ip3hjmeelt7b; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT fk1c2wse5ythrh0ip3hjmeelt7b FOREIGN KEY (branch_id) REFERENCES public.branch(id);


--
-- TOC entry 4862 (class 2606 OID 238157)
-- Name: student_class fk1evep7m7585gnpifv1dg33gb1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_class
    ADD CONSTRAINT fk1evep7m7585gnpifv1dg33gb1 FOREIGN KEY (st_id) REFERENCES public.student(id);


--
-- TOC entry 4853 (class 2606 OID 238107)
-- Name: course_professor fk593ihroxwe5jxdg5a5be0vfev; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_professor
    ADD CONSTRAINT fk593ihroxwe5jxdg5a5be0vfev FOREIGN KEY (course_id) REFERENCES public.course(id);


--
-- TOC entry 4871 (class 2606 OID 254093)
-- Name: branch_class_courses fk5mugan0h2x79yqj54cg79k06u; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.branch_class_courses
    ADD CONSTRAINT fk5mugan0h2x79yqj54cg79k06u FOREIGN KEY (branch_id) REFERENCES public.branch(id);


--
-- TOC entry 4850 (class 2606 OID 238092)
-- Name: class fk5yb4b31948213mn198fkejq70; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.class
    ADD CONSTRAINT fk5yb4b31948213mn198fkejq70 FOREIGN KEY (class_course_id) REFERENCES public.course(id);


--
-- TOC entry 4854 (class 2606 OID 238112)
-- Name: course_professor fk87mc9rcgcw3r4yew53uoi3me9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_professor
    ADD CONSTRAINT fk87mc9rcgcw3r4yew53uoi3me9 FOREIGN KEY (prof_id) REFERENCES public.professor(id);


--
-- TOC entry 4846 (class 2606 OID 238082)
-- Name: attendance fk8vhrq209nnaxv9gsnpyxp2n7a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT fk8vhrq209nnaxv9gsnpyxp2n7a FOREIGN KEY (st_id) REFERENCES public.student(id);


--
-- TOC entry 4867 (class 2606 OID 238182)
-- Name: test_student fk9om83svyvggqqgdqxatxwmtck; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.test_student
    ADD CONSTRAINT fk9om83svyvggqqgdqxatxwmtck FOREIGN KEY (test_id) REFERENCES public.test(id);


--
-- TOC entry 4858 (class 2606 OID 238137)
-- Name: professor fkckr46hdap6wxknmnhd850pbn4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.professor
    ADD CONSTRAINT fkckr46hdap6wxknmnhd850pbn4 FOREIGN KEY (user_id) REFERENCES public.user_data(id);


--
-- TOC entry 4869 (class 2606 OID 238192)
-- Name: user_roles fkcpbpln558xwr5eg987t7jo6gd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkcpbpln558xwr5eg987t7jo6gd FOREIGN KEY (user_id) REFERENCES public.user_data(id);


--
-- TOC entry 4855 (class 2606 OID 238122)
-- Name: course_student fkejube33ubdpqbbwfawn157dcj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_student
    ADD CONSTRAINT fkejube33ubdpqbbwfawn157dcj FOREIGN KEY (st_id) REFERENCES public.student(id);


--
-- TOC entry 4863 (class 2606 OID 238152)
-- Name: student_class fkfyryxclt2okb0bxjfhct0pv5u; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_class
    ADD CONSTRAINT fkfyryxclt2okb0bxjfhct0pv5u FOREIGN KEY (class_id) REFERENCES public.class(id);


--
-- TOC entry 4848 (class 2606 OID 238087)
-- Name: branch fkgo5meyqolq7r08h7x1pt8rwol; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.branch
    ADD CONSTRAINT fkgo5meyqolq7r08h7x1pt8rwol FOREIGN KEY (dept_id) REFERENCES public.department(id);


--
-- TOC entry 4872 (class 2606 OID 254088)
-- Name: branch_class_courses fkhjnodlxt48b9aebqtwrqmkkx7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.branch_class_courses
    ADD CONSTRAINT fkhjnodlxt48b9aebqtwrqmkkx7 FOREIGN KEY (class_courses_id) REFERENCES public.class(id);


--
-- TOC entry 4870 (class 2606 OID 238187)
-- Name: user_roles fkj9553ass9uctjrmh0gkqsmv0d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkj9553ass9uctjrmh0gkqsmv0d FOREIGN KEY (roles_id) REFERENCES public.role(id);


--
-- TOC entry 4861 (class 2606 OID 238147)
-- Name: student fkjat43nirtts18n2bwy1m9afkp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT fkjat43nirtts18n2bwy1m9afkp FOREIGN KEY (user_id) REFERENCES public.user_data(id);


--
-- TOC entry 4868 (class 2606 OID 238177)
-- Name: test_student fkjd72i4alkvtiyooqeodja4q54; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.test_student
    ADD CONSTRAINT fkjd72i4alkvtiyooqeodja4q54 FOREIGN KEY (st_id) REFERENCES public.student(id);


--
-- TOC entry 4864 (class 2606 OID 238162)
-- Name: test fkl1l6sce9s01gs0xn9nw7y4sx9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.test
    ADD CONSTRAINT fkl1l6sce9s01gs0xn9nw7y4sx9 FOREIGN KEY (class_id) REFERENCES public.class(id);


--
-- TOC entry 4856 (class 2606 OID 238117)
-- Name: course_student fklmj50qx9k98b7li5li74nnylb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_student
    ADD CONSTRAINT fklmj50qx9k98b7li5li74nnylb FOREIGN KEY (course_id) REFERENCES public.course(id);


--
-- TOC entry 4847 (class 2606 OID 238077)
-- Name: attendance fklsi77buto2iknunetxvp2vtw3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT fklsi77buto2iknunetxvp2vtw3 FOREIGN KEY (class_id) REFERENCES public.class(id);


--
-- TOC entry 4865 (class 2606 OID 238167)
-- Name: test fkmdosprof1vhis7ky7et2mxcli; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.test
    ADD CONSTRAINT fkmdosprof1vhis7ky7et2mxcli FOREIGN KEY (course_id) REFERENCES public.course(id);


--
-- TOC entry 4851 (class 2606 OID 238097)
-- Name: class fkmmn7a4fg5vx4snc18a1wg7n34; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.class
    ADD CONSTRAINT fkmmn7a4fg5vx4snc18a1wg7n34 FOREIGN KEY (prof_id) REFERENCES public.professor(id) ON DELETE SET NULL;


--
-- TOC entry 4859 (class 2606 OID 238132)
-- Name: professor fkpuhtyuyvfu7i4bu9sroxfcrrx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.professor
    ADD CONSTRAINT fkpuhtyuyvfu7i4bu9sroxfcrrx FOREIGN KEY (dept_id) REFERENCES public.department(id);


--
-- TOC entry 4852 (class 2606 OID 238102)
-- Name: course fkq35kfet2x1flha9h3pxai43hw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT fkq35kfet2x1flha9h3pxai43hw FOREIGN KEY (dept_id) REFERENCES public.department(id);


--
-- TOC entry 4857 (class 2606 OID 238198)
-- Name: department hod_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT hod_id FOREIGN KEY (hod_id) REFERENCES public.professor(id) ON DELETE SET NULL;


--
-- TOC entry 4866 (class 2606 OID 245886)
-- Name: test prof_test; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.test
    ADD CONSTRAINT prof_test FOREIGN KEY (prof_id) REFERENCES public.professor(id) ON DELETE SET NULL;


--
-- TOC entry 5048 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


-- Completed on 2025-10-15 12:13:47

--
-- PostgreSQL database dump complete
--

