SELECT

	CLAS_S.SEMESTER,
	"time",
	COURSE.COURSE_NAME
FROM
	PUBLIC.CLASS CLAS_S
	INNER JOIN PUBLIC.COURSE COURSE ON CLAS_S.CLASS_COURSE_ID = COURSE.ID
	INNER JOIN PUBLIC.STUDENT_CLASS ST_CLASS ON ST_CLASS.CLASS_ID = CLAS_S.ID
	INNER JOIN PUBLIC.STUDENT ST ON ST.ID = ST_CLASS.ST_ID where ST.emailid='heyyou456@gmail.com';